def summon_stone():
    stone = {"god": {"fire": {"2": "summon_stone/fire/god/agnis4.png",
                              "1": "summon_stone/fire/god/agnis5.png"},
                     "water": {"2": "summon_stone/water/god/varuna4.png",
                               "1": "summon_stone/water/god/varuna5.png"},
                     "sand": {"2": "summon_stone/sand/god/titan4.png",
                              "1": "summon_stone/sand/god/titan5.png"},
                     "wind": {"2": "summon_stone/wind/god/zep4.png",
                              "1": "summon_stone/wind/god/zep5.png"},
                     "light": {"2": "summon_stone/light/god/zeus4.png",
                               "1": "summon_stone/light/god/zeus5.png"},
                     "dark": {"2": "summon_stone/dark/god/hades4.png",
                              "1": "summon_stone/dark/god/hades5.png"}},

             "magna": {"fire": {"2": "summon_stone/fire/magna/koro4.png",
                                "1": "summon_stone/fire/magna/koro5.png"},
                       "water": {"2": "summon_stone/water/magna/riva4.png",
                                 "1": "summon_stone/water/magna/riva5.png"},
                       "sand": {"2": "summon_stone/sand/magna/yugu4.png",
                                "1": "summon_stone/sand/magna/yugu5.png"},
                       "wind": {"2": "summon_stone/wind/magna/tiamat4.png",
                                "1": "summon_stone/wind/magna/tiamat5.png"},
                       "light": {"3": "summon_stone/light/magna/syuva3.png",
                                 "2": "summon_stone/light/magna/syuva4.png",
                                 "1": "summon_stone/light/magna/syuva5.png"},
                       "dark": {"2": "summon_stone/dark/magna/serest4.png",
                                "1": "summon_stone/dark/magna/serest5.png"}},

             "provi": {"fire": {"2": "summon_stone/fire/provi/shiva4.png",
                                "1": "summon_stone/fire/provi/shiva5.png"},
                       "water": {"2": "summon_stone/water/provi/europe4.png",
                                 "1": "summon_stone/water/provi/europe5.png"},
                       "sand": {"2": "summon_stone/sand/provi/gobro4.png",
                                "1": "summon_stone/sand/provi/gobro5.png"},
                       "wind": {"2": "summon_stone/wind/provi/grim4.png",
                                "1": "summon_stone/wind/provi/grim5.png"},
                       "light": {"2": "summon_stone/light/provi/rusi4.png",
                                 "1": "summon_stone/light/provi/rusi5.png"},
                       "dark": {"3": "summon_stone/dark/provi/baha3.png",
                                "2": "summon_stone/dark/provi/baha4.png",
                                "1": "summon_stone/dark/provi/baha5.png"}}}
    return stone
